server:
  port: 9090

keycloak:
  realm: e-invoices
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: invoicing-app
  credentials:
    secret: bFWgazKZHLiMdCqjhx2U2dZx8eOyJ67d
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client
